In [1]:
import numpy as np

# -------------------------------
# STEP 1: Patterns (Training Data)
# -------------------------------
patterns = np.array([
    [1, -1, 1, -1],
    [-1, 1, -1, 1],
    [1, 1, -1, -1],
    [-1, -1, 1, 1]
])

# -------------------------------
# STEP 2: Training (Hebbian)
# -------------------------------
n = patterns.shape[1]
W = np.zeros((n, n))

for p in patterns:
    p = p.reshape(n, 1)
    W += np.dot(p, p.T)

np.fill_diagonal(W, 0)

print("Weight Matrix:\n", W)

# -------------------------------
# STEP 3: Activation Function
# -------------------------------
def sign(x):
    return np.where(x >= 0, 1, -1)

# -------------------------------
# STEP 4: Recall (Epoch-wise)
# -------------------------------
def recall(W, X, epochs=10):
    print("\nInitial Input:", X)

    for epoch in range(epochs):
        X_new = sign(np.dot(W, X))

        print(f"Epoch {epoch+1}: {X_new}")

        if np.array_equal(X, X_new):
            print("Stable state reached!")
            break

        X = X_new

    return X

# -------------------------------
# STEP 5: User Input
# -------------------------------
print("\n----- TEST WITH USER INPUT -----")
print("Enter 4 values (+1 or -1):")

user_input = list(map(int, input().split()))
user_input = np.array(user_input)

# Run recall
final_output = recall(W, user_input)

print("\nFinal Recalled Pattern:", final_output)

Weight Matrix:
 [[ 0.  0.  0. -4.]
 [ 0.  0. -4.  0.]
 [ 0. -4.  0.  0.]
 [-4.  0.  0.  0.]]

----- TEST WITH USER INPUT -----
Enter 4 values (+1 or -1):
1 1 -1 -1

Initial Input: [ 1  1 -1 -1]
Epoch 1: [ 1  1 -1 -1]
Stable state reached!

Final Recalled Pattern: [ 1  1 -1 -1]
