In [ ]:
import numpy as np

In [ ]:
# Sign Function
def sign(x):
    return np.where(x >= 0, 1, -1)

In [ ]:
# Taking Input from User
n = int(input("Enter size of X vectors: "))
m = int(input("Enter size of Y vectors: "))

print("\nEnter values in bipolar form (-1 or 1)\n")

print("Enter X1:")
X1 = np.array(list(map(int, input().split())))

print("Enter Y1:")
Y1 = np.array(list(map(int, input().split())))

print("Enter X2:")
X2 = np.array(list(map(int, input().split())))

print("Enter Y2:")
Y2 = np.array(list(map(int, input().split())))

# -----------------------------
# Display Stored Pairs
# -----------------------------
print("\nStored Pattern Pairs:")
print("X1 -> Y1:", X1, "->", Y1)
print("X2 -> Y2:", X2, "->", Y2)


Enter size of X vectors: 3
Enter size of Y vectors: 2

Enter values in bipolar form (-1 or 1)

Enter X1:
1 -1 1
Enter Y1:
1 1
Enter X2:
-1 1 -1
Enter Y2:
-1 -1

Stored Pattern Pairs:
X1 -> Y1: [ 1 -1  1] -> [1 1]
X2 -> Y2: [-1  1 -1] -> [-1 -1]


In [ ]:
# Weight Matrix Calculation
W1 = np.outer(X1, Y1)
W2 = np.outer(X2, Y2)

print("\nOuter Product for Pair 1:\n", W1)
print("Outer Product for Pair 2:\n", W2)

W = W1 + W2
print("\nFinal Weight Matrix W:\n", W)


Outer Product for Pair 1:
 [[ 1  1]
 [-1 -1]
 [ 1  1]]
Outer Product for Pair 2:
 [[ 1  1]
 [-1 -1]
 [ 1  1]]

Final Weight Matrix W:
 [[ 2  2]
 [-2 -2]
 [ 2  2]]


In [ ]:
# Recall from X
def recall_from_X(X, W):
    print("\n--- Recall Y from Given X ---")
    print("Initial X:", X)

    for i in range(10):
        Y = sign(np.dot(X, W))
        print(f"Iteration {i+1} - Y:", Y)

        X_new = sign(np.dot(Y, W.T))
        print(f"Iteration {i+1} - X:", X_new)

        if np.array_equal(X, X_new):
            print("Converged!")
            break

        X = X_new

    return X, Y

# Recall from Y
def recall_from_Y(Y, W):
    print("\n--- Recall X from Given Y ---")
    print("Initial Y:", Y)

    for i in range(10):
        X = sign(np.dot(Y, W.T))
        print(f"Iteration {i+1} - X:", X)

        Y_new = sign(np.dot(X, W))
        print(f"Iteration {i+1} - Y:", Y_new)

        if np.array_equal(Y, Y_new):
            print("Converged!")
            break

        Y = Y_new

    return X, Y

# -----------------------------
# Test with User Input
# -----------------------------
print("\nEnter test X to recall Y:")
test_X = np.array(list(map(int, input().split())))
final_X, final_Y = recall_from_X(test_X, W)

print("\nFinal Output:")
print("Recalled X:", final_X)
print("Recalled Y:", final_Y)

print("\nEnter test Y to recall X:")
test_Y = np.array(list(map(int, input().split())))
final_X2, final_Y2 = recall_from_Y(test_Y, W)

print("\nFinal Output:")
print("Recalled X:", final_X2)
print("Recalled Y:", final_Y2)


Enter test X to recall Y:
1 -1 1

--- Recall Y from Given X ---
Initial X: [ 1 -1  1]
Iteration 1 - Y: [1 1]
Iteration 1 - X: [ 1 -1  1]
Converged!

Final Output:
Recalled X: [ 1 -1  1]
Recalled Y: [1 1]

Enter test Y to recall X:
-1 -1

--- Recall X from Given Y ---
Initial Y: [-1 -1]
Iteration 1 - X: [-1  1 -1]
Iteration 1 - Y: [-1 -1]
Converged!

Final Output:
Recalled X: [-1  1 -1]
Recalled Y: [-1 -1]
