In [ ]:
import numpy as np

# Activation function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def derivative(x):
    return x * (1 - x)

# XOR input and output
X = np.array([[0,0],
              [0,1],
              [1,0],
              [1,1]])

Y = np.array([[0],
              [1],
              [1],
              [0]])

# Initialize weights
np.random.seed(0)
W1 = np.random.rand(2, 2)
W2 = np.random.rand(2, 1)

# Training
for i in range(5000):
    # Forward pass
    H = sigmoid(np.dot(X, W1))
    O = sigmoid(np.dot(H, W2))

    # Error
    error = Y - O

    # Print step-by-step for first few iterations
    if i < 5:
        print(f"\nEpoch {i+1}")
        print("Predicted Output:\n", O)
        print("Actual Output:\n", Y)
        print("Error (Y - O):\n", error)
        print("Mean Error:", np.mean(np.abs(error)))

    # Backpropagation
    dO = error * derivative(O)
    dH = dO.dot(W2.T) * derivative(H)

    # Update weights
    W2 += H.T.dot(dO)
    W1 += X.T.dot(dH)

# Final outputs
print("\n--- After Training ---")
print("Final Predicted Output:\n", O)

# User input
a = int(input("\nEnter first input (0 or 1): "))
b = int(input("Enter second input (0 or 1): "))

# Prediction
inp = np.array([[a, b]])
h = sigmoid(np.dot(inp, W1))
o = sigmoid(np.dot(h, W2))

print("Output:", round(o[0][0]))


Epoch 1
Predicted Output:
 [[0.63059599]
 [0.66432327]
 [0.66869443]
 [0.69531126]]
Actual Output:
 [[0]
 [1]
 [1]
 [0]]
Error (Y - O):
 [[-0.63059599]
 [ 0.33567673]
 [ 0.33130557]
 [-0.69531126]]
Mean Error: 0.4982223878379592

Epoch 2
Predicted Output:
 [[0.60915814]
 [0.63766384]
 [0.64162565]
 [0.66451032]]
Actual Output:
 [[0]
 [1]
 [1]
 [0]]
Error (Y - O):
 [[-0.60915814]
 [ 0.36233616]
 [ 0.35837435]
 [-0.66451032]]
Mean Error: 0.49859474335056836

Epoch 3
Predicted Output:
 [[0.5901726 ]
 [0.61389104]
 [0.61745204]
 [0.63671515]]
Actual Output:
 [[0]
 [1]
 [1]
 [0]]
Error (Y - O):
 [[-0.5901726 ]
 [ 0.38610896]
 [ 0.38254796]
 [-0.63671515]]
Mean Error: 0.49888616877377595

Epoch 4
Predicted Output:
 [[0.57385335]
 [0.59335625]
 [0.59654873]
 [0.61250007]]
Actual Output:
 [[0]
 [1]
 [1]
 [0]]
Error (Y - O):
 [[-0.57385335]
 [ 0.40664375]
 [ 0.40345127]
 [-0.61250007]]
Mean Error: 0.49911211196753796

Epoch 5
Predicted Output:
 [[0.56015173]
 [0.57605525]
 [0.57892421]
 [0.591