In [ ]:
import numpy as np

# Activation Function
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

# Derivative
def sigmoid_derivative(x):
    return x * (1 - x)

# Dataset: Study Hours → Pass(1)/Fail(0)
# (You can explain this easily in viva)
X_original = np.array([[1],
                       [2],
                       [3],
                       [4],
                       [5],
                       [6],
                       [7],
                       [8]])

y = np.array([[0],
              [0],
              [0],
              [0],
              [1],
              [1],
              [1],
              [1]])

# Normalize input
max_val = np.max(X_original)
X = X_original / max_val

# Network Structure
input_neurons = 1
hidden_neurons = 3
output_neurons = 1

# Initialize weights & bias
np.random.seed(1)
wh = np.random.rand(input_neurons, hidden_neurons)
bh = np.random.rand(1, hidden_neurons)
wo = np.random.rand(hidden_neurons, output_neurons)
bo = np.random.rand(1, output_neurons)

learning_rate = 0.1
epochs = 20   # Keep small to display steps

print("----- TRAINING STARTED -----\n")

for epoch in range(epochs):

    # Forward Propagation
    hidden = sigmoid(np.dot(X, wh) + bh)
    output = sigmoid(np.dot(hidden, wo) + bo)

    # Error
    error = y - output

    # Backpropagation
    d_output = error * sigmoid_derivative(output)
    d_hidden = d_output.dot(wo.T) * sigmoid_derivative(hidden)

    # Update weights
    wo += hidden.T.dot(d_output) * learning_rate
    bo += np.sum(d_output, axis=0)
    wh += X.T.dot(d_hidden) * learning_rate
    bh += np.sum(d_hidden, axis=0)

    # Display each epoch
    print(f"Epoch {epoch+1}")
    print("Predicted Output:\n", output)
    print("Error:\n", error)
    print("Mean Error:", np.mean(np.abs(error)))
    print("-"*40)

print("\n----- TRAINING COMPLETED -----\n")
print("Final Output:\n", output)

# -------------------------------
# User Input
# -------------------------------
print("\n----- TEST WITH USER INPUT -----")

hours = float(input("Enter study hours: "))

# Normalize input
user_input = np.array([[hours]]) / max_val

hidden_user = sigmoid(np.dot(user_input, wh) + bh)
output_user = sigmoid(np.dot(hidden_user, wo) + bo)

# Convert to binary result
result = 1 if output_user[0][0] >= 0.5 else 0

print("Predicted Value:", output_user[0][0])
print("Result:", "Pass" if result == 1 else "Fail")

----- TRAINING STARTED -----

Epoch 1
Predicted Output:
 [[0.74057547]
 [0.74248593]
 [0.74436154]
 [0.74619697]
 [0.74798739]
 [0.74972854]
 [0.75141676]
 [0.753049  ]]
Error:
 [[-0.74057547]
 [-0.74248593]
 [-0.74436154]
 [-0.74619697]
 [ 0.25201261]
 [ 0.25027146]
 [ 0.24858324]
 [ 0.246951  ]]
Mean Error: 0.4964297787641101
----------------------------------------
Epoch 2
Predicted Output:
 [[0.65170391]
 [0.65380234]
 [0.655869  ]
 [0.65789761]
 [0.65988236]
 [0.66181805]
 [0.66370008]
 [0.66552451]]
Error:
 [[-0.65170391]
 [-0.65380234]
 [-0.655869  ]
 [-0.65789761]
 [ 0.34011764]
 [ 0.33818195]
 [ 0.33629992]
 [ 0.33447549]]
Mean Error: 0.49604348208758486
----------------------------------------
Epoch 3
Predicted Output:
 [[0.57597883]
 [0.57811931]
 [0.58023239]
 [0.58231134]
 [0.58434989]
 [0.58634234]
 [0.58828357]
 [0.59016914]]
Error:
 [[-0.57597883]
 [-0.57811931]
 [-0.58023239]
 [-0.58231134]
 [ 0.41565011]
 [ 0.41365766]
 [ 0.41171643]
 [ 0.40983086]]
Mean Error: 0.4959