In [ ]:
import numpy as np

# -------------------------------
# Activation Function
# -------------------------------
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# -------------------------------
# Training Data (Example)
# -------------------------------
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

Y = np.array([[0],
              [1],
              [1],
              [0]])   # XOR Output

# -------------------------------
# Network Structure
# -------------------------------
input_neurons = 2
hidden_neurons = 2
output_neurons = 1

# -------------------------------
# Initialize Weights & Bias
# -------------------------------
np.random.seed(0)
W1 = np.random.rand(input_neurons, hidden_neurons)
b1 = np.random.rand(1, hidden_neurons)

W2 = np.random.rand(hidden_neurons, output_neurons)
b2 = np.random.rand(1, output_neurons)

learning_rate = 0.5
epochs = 1000   # small for display

print("----- TRAINING STARTED -----\n")

# -------------------------------
# Training Process
# -------------------------------
for epoch in range(epochs):

    # Forward Propagation
    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    predicted_output = sigmoid(final_input)

    # Error Calculation
    error = Y - predicted_output

    # Backpropagation
    d_output = error * sigmoid_derivative(predicted_output)
    d_hidden = d_output.dot(W2.T) * sigmoid_derivative(hidden_output)

    # Weight Update
    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0)

    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0)

    # Display each epoch
    print(f"Epoch {epoch+1}")
    print("Predicted Output:\n", predicted_output)
    print("Error:\n", error)
    print("Mean Error:", np.mean(np.abs(error)))
    print("-" * 40)

print("\n----- TRAINING COMPLETED -----\n")
print("Final Output:\n", predicted_output)

# -------------------------------
# User Input
# -------------------------------
print("\n----- TEST WITH USER INPUT -----")

a = int(input("Enter first input (0 or 1): "))
b = int(input("Enter second input (0 or 1): "))

user_input = np.array([[a, b]])

# Forward pass for user input
h = sigmoid(np.dot(user_input, W1) + b1)
o = sigmoid(np.dot(h, W2) + b2)

print("Predicted Output:", round(o[0][0]))

Streaming output truncated to the last 5000 lines.
 [0.57487411]]
Error:
 [[-0.19932189]
 [ 0.36886523]
 [ 0.36343285]
 [-0.57487411]]
Mean Error: 0.37662351853963827
----------------------------------------
Epoch 618
Predicted Output:
 [[0.19913882]
 [0.63147106]
 [0.63690115]
 [0.57383216]]
Error:
 [[-0.19913882]
 [ 0.36852894]
 [ 0.36309885]
 [-0.57383216]]
Mean Error: 0.37614969347618105
----------------------------------------
Epoch 619
Predicted Output:
 [[0.19895962]
 [0.63181224]
 [0.63723879]
 [0.57277451]]
Error:
 [[-0.19895962]
 [ 0.36818776]
 [ 0.36276121]
 [-0.57277451]]
Mean Error: 0.37567077698465323
----------------------------------------
Epoch 620
Predicted Output:
 [[0.19878424]
 [0.63215845]
 [0.63758019]
 [0.57170105]]
Error:
 [[-0.19878424]
 [ 0.36784155]
 [ 0.36241981]
 [-0.57170105]]
Mean Error: 0.3751866608085753
----------------------------------------
Epoch 621
Predicted Output:
 [[0.19861261]
 [0.63250985]
 [0.63792548]
 [0.57061167]]
Error:
 [[-0.19861261]
